---
title: "Weekly Assignment 9"
author: "Vincent Espana"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggdist)

prob <- read_csv(("/Users/vince/OneDrive/Documents/GitHub/Data2SciComm/WeeklyAssignments/Assignment9/data/MFIndD_probtask.csv"))

```

```{r dataprep, include = FALSE}

prob_data_mod <- prob %>%
  
  separate(col = left_stim,
           into = c("left_numerator", "left_other"),
           sep = "_") %>%
  
  separate(col = right_stim,
           into = c("right_numerator", "right_other"),
           sep = "_") %>%
  
  mutate(left_numerator = as.numeric(left_numerator),
         left_other = as.numeric(left_other),
         right_numerator = as.numeric(right_numerator),
         right_other = as.numeric(right_other)) %>%
  
  mutate(left_proportion_value = left_numerator/(left_numerator + left_other), 
         right_proportion_value = right_numerator/(right_numerator + right_other)) %>%
  
  mutate(larger_numerator = case_when(left_numerator > right_numerator ~ "left",
                                      left_numerator < right_numerator ~ "right")) %>%
  
  mutate(larger_proportion = case_when(left_proportion_value > right_proportion_value ~ "left",
                                      left_proportion_value < right_proportion_value ~ "right")) %>%
  
  mutate(num_congruent = case_when(larger_numerator == larger_proportion ~ TRUE,
                                   larger_numerator != larger_proportion ~ FALSE))

prob_data_mod

```
# How Do People Think Proportionally With Different Kinds Of Stimuli?

# How Does The Size Of The Components Of The Stimuli Affect Proportional Accuracy?

# Data

```{r}

plot <- prob_data_mod %>% 
  group_by(SubID, condition, num_congruent) %>%
    summarize(prop_corr = mean(correct, na.rm = TRUE), .groups = "drop") %>%
  
 ggplot(aes(y = prop_corr, x = condition, color = num_congruent)) +
  
 stat_halfeye(position = position_dodge(width = 0.5)) +
  
 labs(title = "Proportion Correct by Condition and Number Congruency",
      y = "Proportion Correct",
      x = "Condition") +
  
  theme_minimal() +
  
  scale_color_manual(values = c("TRUE" = "lightblue", "FALSE" = "red"),
                     label = c("TRUE" = "Proportions Congruent", "FALSE" = "Proportions Incongruent"))

plot

```
