---
title: "D2SC ICMA Notebook"
output: html_notebook
author: "Vincent Espana"
date: "`r Sys.Date()`"
---

# ICMA 9/9/2024 

```{r}
plot(cars)
```

# ICMA 9/11/2024

This is where we put plain text

```{r}
# this is where we put r code
```

```{r}
0hno!This_is.a_nightmare <- "hello"
```

```{r}
ohno_this_is_a_nightmare <- "hello"
# dots also work
```

```{r}
2+2
```
```{r}
x <- 2 + 2
```

```{r}
?mean
```

```{r}
mean(c(2, 3, 4))
```

```{r}
myVector <- c(2, 3, 4)
```

```{r}
mean(my_vector)
```
```{r}
my_vector <- c(2, 3, 4)
```

```{r}
?sd
```

```{r}
sd(1:2) ^ 2
```
# ICMA 9/16/2024

```{r}
#install.packages() last time
library(tidyverse)
```

```{r}
#some functions cant be used/need more work
stats::filter()
```

```{r}
#does not work
head(3, billboard)
```


```{r}
#whatever output is first is put into the first position
# 3 will technically be in second position
billboard %>%
  head(3)
```

```{r}
my_numbers <- c(1, 2, 3, 4, 5, 8, 9, 10)
```

```{r}
mean(my_numbers)
```
```{r}
my_numbers %>%
  mean()
```
```{r}
getwd()
```

```{r}
mtcars
```

```{r}
write_csv(mtcars, #object name
          "mtcars_fromR.csv") #file name to save

```

```{r}
mtcars %>%
  rownames_to_column() %>%
  write_csv("mtcars_fromR_rownames.csv")
```

```{r}
mtcars_read <- read_csv("mtcars_fromR_rownames.csv")
```
# ICMA 9/18/2024

```{r}
?ChickWeight
```

```{r}
ChickWeight %>%
  select(weight)
```

```{r}
chick_clean <- ChickWeight %>%
  select(chick_id = Chick,
         diet = Diet,
         age_days = Time,
         weight_gm = weight) #will reorder as well as rename
#will not print because this is only assignment --> will show up in environment
```

equality operator in R is "=="

```{r}
chick_clean %>%
  arrange(chick_id)
```

```{r}
chick_clean %>%
  mutate(weight_per_day = weight_gm/age_days)
```

```{r}
chick_clean %>%
  mutate(weight_lbs = weight_gm/453.6) #mutate will always add to end of dataset 
# doubles will go to infinite within computer bounds

```

```{r}
42/453.6
```
```{r}
chick_clean %>%
  mutate(weight_lbs = weight_gm/453.6) %>%
  group_by(diet, age_days) %>%
  summarize(n = n(),
            mean_wgt_gm = mean(weight_gm,),
            mean_wgt_lbs =mean(weight_lbs)) %>%
  filter(age_days == 20)
```

3 things:
for each diet group
number of chicks, avg gm weight, avg lbs weight
on day 20

```{r}
chick_clean %>%
  filter(age_days == 20) %>%
  mutate(weight_lbs = weight_gm/453.6) %>%
  group_by(diet) %>%
  summarize(n = n(),
            mean_wgt_gm = mean(weight_gm,),
            mean_wgt_lbs =mean(weight_lbs))
```

```{r}
mtcars_modified <- read_csv("mtcars_fromR_rownames.csv")
```

```{r}
glimpse(mtcars_modified)
```

