---
title: "Data Exercise 2"
author: "Vincent Espana"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

# libraries

```{r}

library(tidyverse)

```

# data

how to read in data? --> read_csv
too many files to read --> how can you read 131 files in jumping_data_parker file? --> LOOP, map() function

map(list of files, read_csv

```{r}

files <- list.files(path = "C:/Users/vince/OneDrive/Documents/GitHub/Data2SciComm/DataExercise2/DE2_Parker_UNZIP-BEFORE-USING/jumping_data_parker",
                    pattern = "*.csv",
                    full.names = TRUE)


```

```{r}

files

```


```{r}

convert_columns <- function(file) {
  
  file <- file %>%
  mutate(sex = case_when(sex == FALSE ~ "F",
                         sex == "M" ~ "M"),
         date = as.character(date))
  
}

```

```{r eval = FALSE}

raw_data[[1]] %>%
  mutate(sex = case_when(sex == FALSE ~ "F",
                         sex == "M" ~ "M"))

```

```{r}

raw_data <- map(files, read.csv) %>%
  map(convert_columns) %>%
  bind_rows()

```

```{r}

# inspect data

raw_data %>%
  distinct(condition)

raw_data %>% 
  distinct(laser_trial)

raw_data %>% 
  distinct(sex)

```

#explore the data

```{r}

summary_data <- raw_data %>%
  group_by(subject, distance) %>%
  mutate(succ_rate_NOabort = sum(outcome == 1)/(n() -  sum(outcome == 2)))

```

```{r}

summary_data <- raw_data %>%
  group_by(subject, distance) %>%
  filter(outcome != 2)
  
```


```{r eval = FALSE}

summary_data %>% 
  ggplot(aes(x = succ_rate)) +
  geom_histogram()

```


# plot the data

replicate the figure in the picutre

```{r}

summary_data %>% 
  ggplot(aes(x = distance,
             y = succ_rate, 
             group = subject)) +
  geom_line() +
  ylim(0,1)

```

```{r}

summary_data %>% 
  ggplot(aes(x = distance,
             y = succ_rate, 
             group = subject)) +
  geom_line() +
  ylim(0,1)

```

```{r}

raw_data %>%
  group_by(subject, distance) %>%
  mutate(succ_rate_NOabort = sum(outcome == 1/n() - sum(outcome == 2)))

```

```{r}

raw_data %>%
  group_by(subject, distance) %>%
  filter(outcome %in% c(0, 1)) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(x = distance,
             y = succ_rate,
             group = subject)) +
  geom_line() +
  ylim(0, 1)

```

# make plot look like theirs

```{r}

raw_data %>%
  group_by(subject, distance) %>%
  filter(outcome %in% c(0, 1)) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(x = distance,
             y = succ_rate)) +
  geom_line(aes(group = subject), alpha = 0.3, color = "darkblue") +
  stat_summary(fun.data = "mean_se", geom = "errorbar", width = 0.2, color = "darkblue") +
  stat_summary(fun.y = mean, geom = "line", color = "darkblue") +
  ylim(0, 1) +
  xlim(10, 25) +
  labs(x = "gap distance (cm)",
       y = "success rate") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black", linewidth = 0.5)) +
  annotate(geom = "text", label = "binocular",
           x = 11, y = 0.1, color = "darkblue")

```

# explore something new

```{r}

raw_data %>%
  distinct(experimenter)

```

```{r}

raw_data %>%
  filter(outcome %in% c(0, 1)) %>%
  group_by(subject, experimenter) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(y = succ_rate, 
             x = experimenter)) +
  geom_jitter(alpha = 0.3, width = 0.1, height = 0) +
  ylim(0, 1)

```

